/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package foodtruckmenusystem;

/**
 *
 * @author Sai
 */
public class FoodTruckSelectionScreen extends javax.swing.JFrame {

    /**
     * Creates new form FoodTruckSelectionScreen
     */
    public FoodTruckSelectionScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        breakfastButton = new javax.swing.JButton();
        burgersButton = new javax.swing.JButton();
        crepesButton = new javax.swing.JButton();
        dessertButton = new javax.swing.JButton();
        pizzaButton = new javax.swing.JButton();
        tacoTruckButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        breakfastButton.setText("Breakfast");
        breakfastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakfastButtonActionPerformed(evt);
            }
        });

        burgersButton.setText("Burgers");
        burgersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burgersButtonActionPerformed(evt);
            }
        });

        crepesButton.setText("Crepes");
        crepesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crepesButtonActionPerformed(evt);
            }
        });

        dessertButton.setText("Dessert");
        dessertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dessertButtonActionPerformed(evt);
            }
        });

        pizzaButton.setText("Pizza");
        pizzaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaButtonActionPerformed(evt);
            }
        });

        tacoTruckButton.setText("Taco");
        tacoTruckButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tacoTruckButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(crepesButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(breakfastButton)
                        .addComponent(pizzaButton)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dessertButton)
                    .addComponent(burgersButton)
                    .addComponent(tacoTruckButton))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(breakfastButton)
                        .addComponent(burgersButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dessertButton)
                    .addComponent(pizzaButton))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crepesButton)
                    .addComponent(tacoTruckButton))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void burgersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burgersButtonActionPerformed
        OrderSelectionScreen mainOrder = new OrderSelectionScreen("Burger");
        mainOrder.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_burgersButtonActionPerformed

    private void breakfastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakfastButtonActionPerformed
        OrderSelectionScreen mainOrder = new OrderSelectionScreen("Breakfast");
        mainOrder.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_breakfastButtonActionPerformed

    private void crepesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crepesButtonActionPerformed
        OrderSelectionScreen mainOrder = new OrderSelectionScreen("Crepes");
        mainOrder.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_crepesButtonActionPerformed

    private void pizzaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaButtonActionPerformed
        OrderSelectionScreen mainOrder = new OrderSelectionScreen("Pizza");
        mainOrder.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pizzaButtonActionPerformed

    private void tacoTruckButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tacoTruckButtonActionPerformed
        OrderSelectionScreen mainOrder = new OrderSelectionScreen("Taco");
        mainOrder.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tacoTruckButtonActionPerformed

    private void dessertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dessertButtonActionPerformed
        OrderSelectionScreen mainOrder = new OrderSelectionScreen("Desserts");
        mainOrder.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dessertButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodTruckSelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodTruckSelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodTruckSelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodTruckSelectionScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodTruckSelectionScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton breakfastButton;
    private javax.swing.JButton burgersButton;
    private javax.swing.JButton crepesButton;
    private javax.swing.JButton dessertButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pizzaButton;
    private javax.swing.JButton tacoTruckButton;
    // End of variables declaration//GEN-END:variables
}
